### ISSUE TITLE
minimum dataset?

### ISSUE THREAD

**Issue by chris2286266** [ehn-digital-green-development/hcert-schema#10]
In https://github.com/ehn-digital-green-development/hcert-schema/blob/cb-name/eu_hcert_v1_schema.yaml I noted "optional", when a data field is not mentioned in the appendix of the regulation.

What shall happen to data fields, which are not in the appendix, but in the result of the Semantics workgroup? (e.g. person identifier, gender ...)? (Or which have obviously been forgotten in the appendix?)

**Comment by jschlyter** [comment]
Ping @martin-lindstrom

**Comment by jschlyter** [comment]
@martin-lindstrom what is the required minimal dataset for the `sub`, i.e., what should be `required`?
