### ISSUE TITLE
Missing data types in schema

### ISSUE THREAD

**Issue by martin-lindstrom** [ehn-digital-green-development/hcert-schema#11]
I'm not a JSON schema guy but when I generate Java code from the schema some types maps to Object. So:

- `vac/seq` should be "integer"
- `vac/tot` should be "integer"
- `vac/lot` should be "string" (or?)
- `vac/dat` only specifies format, but no type (add "string"). 
- `vac/adm` has "format=string". Should be "type=string".

For `tst` the "type" is missing and format is used instead. Change.

- `rec/dat` is missing type.
- `rec/cou` specifies format instead of type.

**Comment by jschlyter** [comment]
Please check against https://github.com/ehn-digital-green-development/hcert-schema/pull/4/files

**Comment by jschlyter** [comment]
I can fix the JSON generation as long as the YAM representation is fixed.

**Comment by martin-lindstrom** [comment]
OK, let's wait for PR #4.

**Comment by chris2286266** [comment]
I updated it in https://github.com/ehn-digital-green-development/hcert-schema/tree/cb-name 
Can you review it please (I am AFK now, so feel free ...)

**Comment by jschlyter** [comment]
Merged now, please check @martin-lindstrom

**Comment by martin-lindstrom** [comment]
OK. Closing this.
