### ISSUE TITLE
ISO 3166 Country codes

### ISSUE THREAD

**Issue by jschlyter** [ehn-digital-green-development/hcert-schema#12]
The schema should clarify if the ISO 3166 country codes are in format alpha-2, alpha-3 or numeric? The current examples mentions "xxx" which indicates alpha-3.

**Comment by chris2286266** [comment]
Yes, you are right. I will recheck it with the Semantics document and file a PR later.

**Comment by martin-lindstrom** [comment]
My vote goes to alpha-2 since we need to use that in the CWT anyway. 

Why? The issuer-claim in the CWT will probably be used to find signing certificates, and in a X.509 cert the C RDN normally (always?) has a alpha-2 country code. And there would not be a good idea to mix alpha-2 and alpha-3.

**Comment by martin-lindstrom** [comment]
And concerning the format of the National Person Identifier. I suggest `XX:NUMBER`. It's more clear and easier for a human to parse.

**Comment by jschlyter** [comment]
@chris2286266 please check if `{iso3166 alpha-2}:NUMBER` is ok

**Comment by chris2286266** [comment]
I rechecked it with WG-Semantic document: It comes from HL7, i'm afraid. Source is https://terminology.hl7.org/2.1.0/CodeSystem-v2-0203.html - there it says alpha-3
hmmm ... I's suggest, we leave it as is for the moment. Even if it does not look perfect ...

**Comment by jschlyter** [comment]
Clarified via ec0d2340ec8f51f9078485aa3c345f2993a9878b
