### ISSUE TITLE
Consider support for schema version draft-7

### ISSUE THREAD

**Issue by Razumain** [ehn-digital-green-development/hcert-schema#13]
While testing and viewing this schema using my available tools, I discovered that none of them supported the latest schema version 2020-12, used here.

Looking at the current support status: https://json-schema.org/implementations.html

It seems that most (including) my current tool Oxygen, supports up to version draft-7 (http://json-schema.org/draft-07/schema)

The only thing that makes the current schema not compatible with draft-7 is the use of the "example" keyword.

Given the current status, wouldn't it be wise to use draft-7 schema instead in order to allow a wider array of tools?
The examples could easily be moved into the descriptive text, even though that is not as nice.

**Comment by Razumain** [comment]
My bad. I also realise that the keyword minimum is not supported in draft-7.
That may be more serious.

**Comment by Razumain** [comment]
Just in case you are interested in a version compliant with draft-7. Here examples and minimum values are moved to the description instead.

[eu_hcert_v1_schema-draft-7.txt](https://github.com/ehn-digital-green-development/hcert-schema/files/6306308/eu_hcert_v1_schema-draft-7.txt)

**Comment by jschlyter** [comment]
I can update the script to render dual JSON-schema versions so we can keep the YAML master as it is.

**Comment by chris2286266** [comment]
Yes please @jschlyter

**Comment by jschlyter** [comment]
Fixed.
