### ISSUE TITLE
Change title on schema

### ISSUE THREAD

**Issue by martin-lindstrom** [ehn-digital-green-development/hcert-schema#14]
An implementation detail, but if you generate code from the JSON schema the class names are taken from the "title" (anyway for the jsonschema2pojo-maven-plugin maven plugin).

The main class will be named, `DGCDigitalGreenCertificate` since the title is "DGC - Digital Green Certificate". A bit superfluous.

Suggestion. Change title to "Digital Green Certificate" and use DGC in the comment.

**Comment by chris-baumann-at** [comment]
+1

**Comment by jschlyter** [comment]
Closed via 71e5a00d9d2aaed909c2a9b5039ad9f5597933be
