### ISSUE TITLE
Bring it to 1.0 ...

### ISSUE THREAD

**Issue by chris2286266** [ehn-digital-green-development/hcert-schema#15]
Should we bring the schema now to Version 1.0 and tell Martin Mitev about?

Who should do this? I's suggest @dirkx 

Regards,
Chris

**Comment by dirkx** [comment]
Is fine - but we need an expert like @gcangiolo to make sure it is absolutely right about https://github.com/ehn-digital-green-development/hcert-schema.

Dw

**Comment by jschlyter** [comment]
- Array of `tst` and `rec`to make them similar to `vac
- Close minimum dataset
- Close the partial matching issue

then we're done I think. Also, test the schema with some other tool - both the 2020-12 and draft7 versions.

**Comment by dirkx** [comment]
Hi Dirk,

just to better understand, since this schema is not FHIR, which kind of
support do you expect on my side ?

Providing a mapping from the FHIR resources to the schema ?
Make some other kind of cross-check ?

Thanks,
Giorgio

-----Messaggio originale-----
Da: Dirk-Willem van Gulik ***@***.***> 
Inviato: mercoledì 14 aprile 2021 13:24
A: ehn-digital-green-development/hcert-schema
***@***.***>
Cc: ehn-digital-green-development/hcert-schema
***@***.***>; Mention ***@***.***>;
Giorgio Cangioli ***@***.***>
Oggetto: Re: [ehn-digital-green-development/hcert-schema] Bring it to 1.0
... (#15)

Is fine - but we need an expert like @gcangiolo to make sure it is
absolutely right about
https://github.com/ehn-digital-green-development/hcert-schema.

Dw

**Comment by fredriklj** [comment]
I guess we now have to finalise it as version 1.0. Who can make an assessment on the conformance between the schema and what has been drafted by the semantic group?

ping @dirkx @gabywh @martin-lindstrom @jschlyter

**Comment by chris2286266** [comment]
Hi all,
I updated it with the topics discussed today:
https://github.com/ehn-digital-green-development/hcert-schema/blob/cert-meta/eu_dgc_v1_schema.yaml
I also aligned it with the latest document of the semantics colleagues (from 2021-04-14) some days ago.

So please someone check it, that we can finalise it asap.

THX

**Comment by jschlyter** [comment]
All merged now by request from @martin-lindstrom, we'll handle any fallout in main.

**Comment by gabywh** [comment]
The "official" one is on ms-teams, I'm working on that, also spoke to 
Hynek earlier this morning re semantic-sg and what has been decided there

I'm trying to pull all strands together inclusive of proposed EU 
legislation, without re-inventing any wheels.

I'm aiming to have to have a version ready tomorrow a.m. on ms-teams, 
will let you know

Gaby

Op 19-04-2021 om 12:31 schreef Fredrik Ljunggren:

**Comment by thinkberg** [comment]
+1 🙏

**Comment by gabywh** [comment]
> Hi Dirk, just to better understand, since this schema is not FHIR, which kind of support do you expect on my side ? Providing a mapping from the FHIR resources to the schema ? Make some other kind of cross-check ? Thanks, Giorgio
> […](#)
> -----Messaggio originale----- Da: Dirk-Willem van Gulik ***@***.***> Inviato: mercoledì 14 aprile 2021 13:24 A: ehn-digital-green-development/hcert-schema ***@***.***> Cc: ehn-digital-green-development/hcert-schema ***@***.***>; Mention ***@***.***>; Giorgio Cangioli ***@***.***> Oggetto: Re: [ehn-digital-green-development/hcert-schema] Bring it to 1.0 ... (#15) Is fine - but we need an expert like @gcangiolo to make sure it is absolutely right about https://github.com/ehn-digital-green-development/hcert-schema. Dw

====

@gcangiolo: this schema is indeed completely separate to FHIR and the two are only related in so far as we have the practical question: once we have this schema defined, how do get the data from e.g. an IIS supporting FHIR? I'll catch up with Christof and yourself on this one (the Word doc thing...). Gaby.

**Comment by chris2286266** [comment]
as everything seems clear, i'll close it now ...
