### ISSUE TITLE
Property cert.ty needs clarification

### ISSUE THREAD

**Issue by jschlyter** [ehn-digital-green-development/hcert-schema#19]

**Comment by chris-baumann-at** [comment]
This is based on the assumption, that a DGC contains exactly one "type" of data: vaccination, test or recovery, as we interpret the regulation.
If so, it allows a detection of the type by reading just this property instead of "trying" if it is a vac, tst or rec.

**Comment by jschlyter** [comment]
I would not assume that, even though it may be a policy right now, and just remove the property. It is obvious when looking at the data structure what it contains, we do not need to waste space to repeat that IMHO.
