### ISSUE TITLE
Enum for gender

### ISSUE THREAD

**Issue by jschlyter** [ehn-digital-green-development/hcert-schema#27]
To simplify for verifiers, it would be nice if we can define `gender` as an enum. What values are permitted?

**Comment by jschlyter** [comment]
ping @chris2286266 @gabywh @martin-lindstrom

**Comment by chris2286266** [comment]
according to valuesets from semantics:
male, female, other, unknown

**Comment by gabywh** [comment]
Gender dropped

Op 19-04-2021 om 14:30 schreef chris2286266:

**Comment by jschlyter** [comment]
> Gender dropped

@gabywh, gender removed via #30
