### ISSUE TITLE
Partial matching of name/dob

### ISSUE THREAD

**Issue by jschlyter** [ehn-digital-green-development/hcert-schema#3]
@dirkx has indicate that partial matching for names and date of birth might be needed. Perhaps we can use:

- `pfn` (partial first name)
- `pgn` (partial given name)
- `pdob` (partial date of birth), an object with separate y/m/d (integers) properties

**Comment by dirkx** [comment]
Is this a good idea ? Not all countries have a solid concept of a first- and last-name (or may swap these; or just have either).

Ultimately this is a display string - for the verifier to be used to compare such against the identity document of the citizen.

So I would argue that the simplest is to simply have 'Name' and a 'date of Birth' field -- and leave it to the member state to populate this according to what aligns well with how they reflect these on ID cards.

Secondly - I would also argue that such a (first/last name) split is only needed if the data is likely to be processed and stored in something like a structured format.  As the European Directive expressly forbids that - I guess it is not that needed to structure the data this much.

**Comment by jschlyter** [comment]
In #1 @chris2286266 made the argument that the name should be split into fn/gn as this is already done in the passport and national ID world. I see no problem with that, either for all names or as an option to a composite name field. If we have this, we should have any partial fields split as well. One could also use conventions like "Ja* Sc*", but perhaps such a name field should also be separate to indicate that it contains a partial match (pattern).

For partial date of birth matching, having separate fields helps UI design a lot as we have no common partial date format.

Automatic or manual matching of these fields with passport/identity card is a IMHO a separate issue. Even though not stored persistently, there will most certainly be automatic matching implemented by validators that can read passports and national ID cards.

**Comment by dirkx** [comment]
While I appreciate that most countries have first & last names (and sometimes middle names) - I do not think this is universal. It is pretty common to have "Single names" or "no given name" situation.  

In those cases, in most passport/ID card systems the entire name is then usually designated as the "Primary Identifier" (last name) and often entered in a lot of systems that do have a first/last name as the last name with a '.' or 'FULL STOP' in the first name field.

And the medical systems tend to be more localised that the international systems & the source of ourdata.

**Comment by jschlyter** [comment]
> While I appreciate that most countries have first & last names (and sometimes middle names) - I do not think this is universal. It is pretty common to have "Single names" or "no given name" situation.

[I agree.](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/)

> In those cases, in most passport/ID card systems the entire name is then usually designated as the "Primary Identifier" (last name) and often entered in a lot of systems that do have a first/last name as the last name with a '.' or 'FULL STOP' in the first name field.
> 
> And the medical systems tend to be more localised that the international systems & the source of ourdata.

Let's move this part of the discussion to PR #4. Once that has been resolved, this issue can move forward.

**Comment by jschlyter** [comment]
#4 closed. @dirkx, your move.

**Comment by jschlyter** [comment]
Closing this one, may be addressed in a later version of the payload.
