### ISSUE TITLE
Is the addition of transliteration really necessary?

### ISSUE THREAD

**Issue by thinkberg** [ehn-digital-green-development/hcert-schema#31]
This is a machine readable certificate that is encoded in UTF-8 anyway. It adds to the size and is probably done automatic anyway and can easily be done on a verifier side.

**Comment by fredriklj** [comment]
I completely agree with you, and tried to argue this on the meeting this monday. But some argued it may be too hard for some implementors of Verifier Apps to manage it. So the compromise was to allow it to be included in the data structure.
