### ISSUE TITLE
Subject nationality needed?

### ISSUE THREAD

**Issue by jschlyter** [ehn-digital-green-development/hcert-schema#5]
Can a Swedish citizen acquire a health certificate from the Netherlands? If so, do also need to include the nationality of the subject in the schema?

**Comment by dirkx** [comment]
Yes they can - and the system that would issue the certificates would not really know this. So you'd have to guess it from a swedish sounding name. In some cases (e.g. icelandic Þ or  german ß) it would get transliterated fairly randomly.

**Comment by martin-lindstrom** [comment]
If you as a dutch citizen living in Sweden and is officially registered you get a Swedish personal identity number. Given that you can get a Swedish eID and authenticate to the Green pass webservice. And get a HC cert issued. The thing is that the service prompts for your passport number, but the webservice doesn't necessarily require the passport to be a Swedish passport.

**Comment by chris2286266** [comment]
DGC is also for testing. So if a german tourist comes to Austria and undergoes a Covid19-Test here, he receives a test certificate from AT ...

**Comment by jschlyter** [comment]
So for both password numbers and national identity numbers we need to have a scope, e.g. issuing country.

**Comment by dirkx** [comment]
If you assume they have to be on there. 

Most medical systems that produce these won't have those. They are too short lived. 

You have an identity card of passport during travel that shows this.

So we are back to - it is probably quite enough to just have first/lastname (parts/elements) and (some of) the DOB to sufficiently link you to those identity cards.

**Comment by sondaica** [comment]
issuing country of the id might not be the same as nationality so the information should be on the id part if it should be added in the dataset and not on subject.

**Comment by jschlyter** [comment]
Yes, the national identity number and national identity number issuer needs to be handled as a tuple. A Dutch citizen can have  a Swedish NIN issued in a Norwegian hcert.

**Comment by dirkx** [comment]
I think this is getting fairly refined - and almost at the level where you ready this for fully automatic, unattended validation. I would simply see this at as a string which the border agent intelligently compares to what he has at hand.  With his or her eyeballs. And leave all else out.

**Comment by martin-lindstrom** [comment]
The Swedish DGC-issuing service will only include ID-number that are Swedish. Independently of the citizenship of the person. 

In order to use the Swedish DGC-issuing service you need to authenticate with a Swedish eID (that carries a Swedish personal identity number). This will be the ID included in the DGC. It says nothing about citizenship, but it tells that the holder of the DGC is a registered Swedish resident.

**Comment by martin-lindstrom** [comment]
> Yes, the national identity number and national identity number issuer needs to be handled as a tuple. A Dutch citizen can have a Swedish NIN issued in a Norwegian hcert.

Really? I would assume that a Swedish personal identity number isn't valid for the Norwegian DGC-issuer.

**Comment by jschlyter** [comment]
> Really? I would assume that a Swedish personal identity number isn't valid for the Norwegian DGC-issuer.

That may be true, but is such a property implicit or explicit? IMHO it is more clear to say that the subject has _Swedish_ national identity number X, than just simply national identity number X. The same goes for passports, Swedish passport number Y is better than passport number Y (since the id space for passports is per issuing country, not global).
