### ISSUE TITLE
Arrays in hCerts

### ISSUE THREAD

**Issue by chris2286266** [ehn-digital-green-development/hcert-schema#9]
It is clear, that the "vac" element has to contain an array for more than one vaccination.

But what about the test and recovery elements?

A test result is valid for a couple of days at maximum and the next test superseeds the last one. So why should more than one (e.g. old) test results be stored in a hCert?

Recovery: Contains "Date of first positive test result". As there can only be one "first", storing more than one recovery statement in a hCert is senslessless imho.

Can we discuss/decide this in this github group? Or shall we ask e.g. Stefanie from the Semantic Subgroup?

**Comment by jschlyter** [comment]
I would guess multiple `tst` and `rec` also makes sense as you can recover from multiple `dis`.

**Comment by chris2286266** [comment]
At the moment everything is defined for one dis: "840539006" which is Covid-19. I guess, if the current hCert ever is extended for further diseases, a lot of other changes would be necessary ...

**Comment by jschlyter** [comment]
I'd like to reopen this just move tst and rec to arrays, would that be a problem @chris2286266 ?

**Comment by chris2286266** [comment]
Not a technical problem. I just think, it is semantically wrong to have more than one "recovery of the same disease which ends on exactly the same date" more than once.

**Comment by chris2286266** [comment]
But I think it is more important to come to a V1.0 than to get every aspect 100% correct, which is impossible anyway ;-)

**Comment by jschlyter** [comment]
Then I suggest we include this and let the semantics handle it later. Better to get the overall datatype right now.
